### ISSUE TITLE
Add prompt for user's e-mail address

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#39]
Needed for when we push the badge

**Comment by JoePrezioso** [comment]
Rory and I are currently working on that. Given that we already have code for a search bar, it shouldn't be too difficult to set up another bar for a user to enter their email into and then pass that in when the user presses the "push" button (Note: "push" is a placeholder label).

Question: does this mean that we can just set up the button so that, if the user hasn't entered an email address, the button does nothing (or tells the user that he/she needs to enter an email address)?

**Comment by JoePrezioso** [comment]
We now have a text field for e-mail. We can also check for the presence or absence of text. 

So, now we need to pass the email into the function to push to open badges (not yet coded) and possibly check to see if the email is even valid (time-permitting).

**Comment by JoePrezioso** [comment]
Closing for now. If we have problems with the prompt later, we can re-open the issue.
